# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cab54f3fbdc5ed0497d7c0436fbd56e04357dd5dbb1111c8a8628992997dc60acfab3a784a21c31a8ac1e18669285dfeeb6b6b649210d52dfc94c4c116f8d17

test:
  secret_key_base: 75744d20fea763a6c8cfdc34f8e16e785d6c08be215d44659e22f17e428fe8b89a054e619be1c52413325241915ee687fc2d10b21099e565b57cea7f3f0b29a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
